### PR TITLE
integrate guided super resolution option

### PR DESCRIPTION
**Pull request by nandometzger**
First: I had to disable the `enable_xformers` flag, for the cases where cuda is not available.

### CODE REVIEW

**Comment by nandometzger** [comment]
I did not have a GPU to test the implementation. Maybe somebody could check with some more samples to verify.
Basically, you can now set the flag `--guided_upsampling`, and the script will perform 4000 iterations of anisotropic diffusion.

Things to do:

- [ ] Verify the usefulness of the outputs on a broader range of samples
- [ ] Make downloading the DADA checkpoints simpler. For now, I used the official DIMLx4 checkpoint from

**Comment by nandometzger** [comment]
left: guided upsampling
right: nearest neighbor upsampling
image

**Comment by nandometzger** [comment]
example_6_pred_source
example_6_pred_colored

**Comment by nandometzger** [comment]
it also smooths out the fur a lot
image

**Comment by YuxuanSnow** [comment]
> it also smooths out the fur a lot image

left is guided sampling and right is original NN sampling? Isn't the right one better due to not oversmoothed?

**Comment by areykills** [comment]
> First: I had to disable the `enable_xformers` flag, for the cases where cuda is not available.

♥

**Pull request closed without merging**
